pages:
  stage: deploy
  script:
    - echo 'deploy public pages'
  artifacts:
    paths:
      - public
  only:
    - master

install:
  stage: build
  image: maxtori/opam-postgres:debian
  cache:
    paths :
      - _opam/
  script:
    - if [ ! -d _opam ]; then opam switch create --no-install . ocaml-system; fi
    - eval $(opam env)
    - make deps
    - make
  only:
    - merge_requests
