pages:
  stage: deploy
  script:
    - echo 'deploy public pages'
  artifacts:
    paths:
      - public
  only:
    - master

check:
  stage: build
  image: maxtori/opam-postgres:debian
  cache:
    paths :
      - _opam/
  script:
    - if [ ! -d _opam ]; then opam switch create --no-install . ocaml-system; fi
    - eval $(opam env)
    - sudo apt-get install -y postgresql-13-pgmp npm
    - createdb crawlori && sudo -i -u functori -- psql crawlori -c 'create extension if not exists pgmp;'
    - make deps
    - POSTGRES_USER=functori make pgmp-extension
    - make
    - sudo npm install -g typescript
    - make ts-deps
    - make ts
  only:
    - merge_requests

docker:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
