FROM functori/rarible-deps:latest as compilation

RUN $(pg_config --bindir)/pg_ctl start -D ../data && \
eval $(opam env) && \
opam update && opam upgrade && \
echo 'DB=postgres' > Makefile.config && \
dropdb postgres && createdb postgres && \
make clean && \
make

FROM debian:latest as target
LABEL Description="rarible container" Vendor="Functori"

RUN apt-get update && apt-get install -y librdkafka-dev libcurl4-gnutls-dev
RUN addgroup --system postgres && adduser --system --group --shell /bin/sh postgres && \
    echo 'postgres ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
USER postgres
WORKDIR /home/postgres
COPY --from=compilation --chown=postgres /home/functori/rarible/deployment/crawler_config.json /home/functori/rarible/_bin/* /home/functori/rarible/scripts/reset_royalties.sh /home/postgres/
CMD [ "./crawler", "crawler_config.json" ]
