FROM maxtori/opam-postgres:debian as compilation

COPY --chown=functori . ./rarible
WORKDIR ./rarible
RUN $(pg_config --bindir)/pg_ctl start -D ../data && \
opam switch create --no-install . ocaml-system && \
eval $(opam env) && \
make deps && \
opam install httpaf-lwt-unix && \
echo 'DB=postgres' > Makefile.config && \
dropdb postgres && \
make clean && \
make

FROM debian:latest as target
LABEL Description="rarible container" Vendor="Functori"

RUN apt-get update && apt-get install -y librdkafka-dev libcurl4-gnutls-dev
RUN addgroup --system postgres && adduser --system --group --shell /bin/sh postgres && \
    echo 'postgres ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
USER postgres
WORKDIR /home/postgres
COPY --from=compilation --chown=postgres /home/functori/rarible/deployment/crawler_config.json /home/functori/rarible/_bin/* /home/postgres/
CMD [ "./crawler", "crawler_config.json" ]
