FROM maxtori/opam-postgres:debian as compilation

COPY --chown=functori . ./rarible
WORKDIR ./rarible
RUN $(pg_config --bindir)/pg_ctl start -D ../data && \
opam switch create --no-install . ocaml-system && \
eval $(opam env) && \
sudo apt-get install postgresql-13-pgmp && \
createdb crawlori && sudo -i -u functori -- psql crawlori -c 'create extension if not exists pgmp;' && \
make deps && \
POSTGRES_USER=functori make pgmp-extension && \
make clean && \
make

FROM debian:latest as target
LABEL Description="rarible container" Vendor="Functori"

RUN apt-get update && apt-get install -y librdkafka-dev libcurl4-gnutls-dev
RUN addgroup --system functori && adduser --system --group --shell /bin/sh functori && \
    echo 'functori ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
USER functori
WORKDIR /home/functori
COPY --from=compilation --chown=functori /home/functori/rarible/deployment/crawler_config.json /home/functori/rarible/_bin/* /home/functori/
CMD [ "./crawler", "crawler_config.json" ]
