FROM functori/opam-postgres:debian as compilation

COPY --chown=functori . ./rarible
WORKDIR ./rarible
RUN $(pg_config --bindir)/pg_ctl start -D ../data && \
opam switch create --no-install . ocaml-system && \
eval $(opam env) && \
make deps && \
opam install httpaf-lwt-unix
