openapi: 3.0.3
info:
  title: Tezos Rarible Kafka Types
  version: "0.1"
paths:
  /kafka/item:
    summary: kafka_item
    get:
      tags:
      - kafka-controller
      summary: kafka_item
      operationId: kafka_item
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftItemEvent'
      security: []
  /kafka/order:
    summary: kafka_order
    get:
      tags:
      - kafka-controller
      summary: kafka_order
      operationId: kafka_order
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderEvent'
      security: []
  /kafka/ownership:
    summary: kafka_ownership
    get:
      tags:
      - kafka-controller
      summary: kafka_ownership
      operationId: kafka_ownership
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NftOwnershipEvent'
      security: []
  /kafka/activity:
    summary: kafka_activity
    get:
      tags:
      - kafka-controller
      summary: kafka_activity
      operationId: kafka_activity
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityType'
      security: []
components:
  schemas:
    ActivityType:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date-time
        source:
          type: string
        type:
          oneOf:
          - $ref: '#/components/schemas/OrderActivityType'
          - $ref: '#/components/schemas/NftActivityType'
      required:
      - type
      - source
      - date
      - id
      additionalProperties: false
    Address:
      type: string
    Asset:
      type: object
      properties:
        assetType:
          $ref: '#/components/schemas/AssetType'
        value:
          $ref: '#/components/schemas/BigDecimal'
      required:
      - value
      - assetType
      additionalProperties: false
    AssetType:
      oneOf:
      - $ref: '#/components/schemas/XTZAssetType'
      - $ref: '#/components/schemas/FA_1_2AssetType'
      - $ref: '#/components/schemas/FA_2AssetType'
    BigDecimal:
      type: string
    BigInteger:
      type: string
    BlockNumber:
      type: integer
      minimum: 0
      maximum: 9007199254740992
    Burn:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - burn
        owner:
          $ref: '#/components/schemas/Address'
        contract:
          $ref: '#/components/schemas/Address'
        tokenId:
          $ref: '#/components/schemas/BigInteger'
        value:
          $ref: '#/components/schemas/BigInteger'
        transactionHash:
          $ref: '#/components/schemas/Word'
        blockHash:
          $ref: '#/components/schemas/Word'
        blockNumber:
          $ref: '#/components/schemas/BlockNumber'
      required:
      - blockNumber
      - blockHash
      - transactionHash
      - value
      - tokenId
      - contract
      - owner
      - '@type'
      additionalProperties: false
    Edpk:
      type: string
    Edsig:
      type: string
    FA_1_2AssetType:
      type: object
      properties:
        assetClass:
          type: string
          enum:
          - FA_1_2
        contract:
          $ref: '#/components/schemas/Address'
      required:
      - contract
      - assetClass
      additionalProperties: false
    FA_2AssetType:
      type: object
      properties:
        assetClass:
          type: string
          enum:
          - FA_2
        contract:
          $ref: '#/components/schemas/Address'
        tokenId:
          $ref: '#/components/schemas/BigInteger'
      required:
      - tokenId
      - contract
      - assetClass
      additionalProperties: false
    Mint:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - mint
        owner:
          $ref: '#/components/schemas/Address'
        contract:
          $ref: '#/components/schemas/Address'
        tokenId:
          $ref: '#/components/schemas/BigInteger'
        value:
          $ref: '#/components/schemas/BigInteger'
        transactionHash:
          $ref: '#/components/schemas/Word'
        blockHash:
          $ref: '#/components/schemas/Word'
        blockNumber:
          $ref: '#/components/schemas/BlockNumber'
      required:
      - blockNumber
      - blockHash
      - transactionHash
      - value
      - tokenId
      - contract
      - owner
      - '@type'
      additionalProperties: false
    NftActivityElt:
      type: object
      properties:
        owner:
          $ref: '#/components/schemas/Address'
        contract:
          $ref: '#/components/schemas/Address'
        tokenId:
          $ref: '#/components/schemas/BigInteger'
        value:
          $ref: '#/components/schemas/BigInteger'
        transactionHash:
          $ref: '#/components/schemas/Word'
        blockHash:
          $ref: '#/components/schemas/Word'
        blockNumber:
          $ref: '#/components/schemas/BlockNumber'
      required:
      - blockNumber
      - blockHash
      - transactionHash
      - value
      - tokenId
      - contract
      - owner
      additionalProperties: false
    NftActivityType:
      oneOf:
      - $ref: '#/components/schemas/Mint'
      - $ref: '#/components/schemas/Burn'
      - $ref: '#/components/schemas/Transfer'
    NftItem:
      type: object
      properties:
        id:
          type: string
        contract:
          $ref: '#/components/schemas/Address'
        tokenId:
          $ref: '#/components/schemas/BigInteger'
        creators:
          type: array
          items:
            $ref: '#/components/schemas/Part'
        supply:
          $ref: '#/components/schemas/BigInteger'
        lazySupply:
          $ref: '#/components/schemas/BigInteger'
        owners:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        royalties:
          type: array
          items:
            $ref: '#/components/schemas/Part'
        date:
          type: string
          format: date-time
        mintedAt:
          type: string
          format: date-time
        deleted:
          type: boolean
        meta:
          $ref: '#/components/schemas/NftItemMeta'
      required:
      - deleted
      - mintedAt
      - date
      - royalties
      - owners
      - lazySupply
      - supply
      - creators
      - tokenId
      - contract
      - id
      additionalProperties: false
    NftItemAttribute:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
        type:
          type: string
        format:
          type: string
      required:
      - key
      additionalProperties: false
    NftItemEvent:
      type: object
      properties:
        eventId:
          type: string
        itemId:
          type: string
        type:
          type: string
          enum:
          - UPDATE
          - DELETE
        item:
          $ref: '#/components/schemas/NftItem'
      required:
      - item
      - type
      - itemId
      - eventId
      additionalProperties: false
    NftItemMeta:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/NftItemAttribute'
        image:
          type: string
        animation:
          type: string
      required:
      - name
      additionalProperties: false
    NftOwnership:
      type: object
      properties:
        id:
          type: string
        contract:
          $ref: '#/components/schemas/Address'
        tokenId:
          $ref: '#/components/schemas/BigInteger'
        owner:
          $ref: '#/components/schemas/Address'
        creators:
          type: array
          items:
            $ref: '#/components/schemas/Part'
        value:
          $ref: '#/components/schemas/BigInteger'
        lazyValue:
          $ref: '#/components/schemas/BigInteger'
        date:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
      required:
      - createdAt
      - date
      - lazyValue
      - value
      - creators
      - owner
      - tokenId
      - contract
      - id
      additionalProperties: false
    NftOwnershipEvent:
      type: object
      properties:
        eventId:
          type: string
        ownershipId:
          type: string
        type:
          type: string
          enum:
          - UPDATE
          - DELETE
        ownership:
          $ref: '#/components/schemas/NftOwnership'
      required:
      - ownership
      - type
      - ownershipId
      - eventId
      additionalProperties: false
    Order:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/OrderRaribleV2DataV1'
        maker:
          $ref: '#/components/schemas/Address'
        makerEdpk:
          $ref: '#/components/schemas/Edpk'
        taker:
          $ref: '#/components/schemas/Address'
        takerEdpk:
          $ref: '#/components/schemas/Edpk'
        make:
          $ref: '#/components/schemas/Asset'
        take:
          $ref: '#/components/schemas/Asset'
        fill:
          $ref: '#/components/schemas/BigInteger'
        start:
          type: integer
          minimum: 0
          maximum: 9007199254740992
        end:
          type: integer
          minimum: 0
          maximum: 9007199254740992
        makeStock:
          $ref: '#/components/schemas/BigInteger'
        cancelled:
          type: boolean
        salt:
          $ref: '#/components/schemas/Word'
        signature:
          $ref: '#/components/schemas/Edsig'
        createdAt:
          type: string
          format: date-time
        lastUpdateAt:
          type: string
          format: date-time
        hash:
          $ref: '#/components/schemas/Word'
        makeBalance:
          $ref: '#/components/schemas/BigInteger'
        priceHistory:
          type: array
          items:
            $ref: '#/components/schemas/OrderPriceHistoryRecord'
        status:
          $ref: '#/components/schemas/OrderStatus'
        type:
          type: string
          enum:
          - RARIBLE_V2
      required:
      - type
      - hash
      - lastUpdateAt
      - createdAt
      - signature
      - salt
      - cancelled
      - makeStock
      - fill
      - take
      - make
      - makerEdpk
      - maker
      - data
      additionalProperties: false
    OrderActivityBid:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - bid
        hash:
          $ref: '#/components/schemas/Word'
        maker:
          $ref: '#/components/schemas/Address'
        make:
          $ref: '#/components/schemas/Asset'
        take:
          $ref: '#/components/schemas/Asset'
        price:
          $ref: '#/components/schemas/BigDecimal'
      required:
      - price
      - take
      - make
      - maker
      - hash
      - '@type'
      additionalProperties: false
    OrderActivityCancelBid:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - cancel_bid
        hash:
          $ref: '#/components/schemas/Word'
        maker:
          $ref: '#/components/schemas/Address'
        make:
          $ref: '#/components/schemas/AssetType'
        take:
          $ref: '#/components/schemas/AssetType'
        transactionHash:
          $ref: '#/components/schemas/Word'
        blockHash:
          $ref: '#/components/schemas/Word'
        blockNumber:
          $ref: '#/components/schemas/BlockNumber'
        logIndex:
          type: integer
          minimum: -1073741824
          maximum: 1073741823
      required:
      - logIndex
      - blockNumber
      - blockHash
      - transactionHash
      - take
      - make
      - maker
      - hash
      - '@type'
      additionalProperties: false
    OrderActivityCancelList:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - cancel_list
        hash:
          $ref: '#/components/schemas/Word'
        maker:
          $ref: '#/components/schemas/Address'
        make:
          $ref: '#/components/schemas/AssetType'
        take:
          $ref: '#/components/schemas/AssetType'
        transactionHash:
          $ref: '#/components/schemas/Word'
        blockHash:
          $ref: '#/components/schemas/Word'
        blockNumber:
          $ref: '#/components/schemas/BlockNumber'
        logIndex:
          type: integer
          minimum: -1073741824
          maximum: 1073741823
      required:
      - logIndex
      - blockNumber
      - blockHash
      - transactionHash
      - take
      - make
      - maker
      - hash
      - '@type'
      additionalProperties: false
    OrderActivityList:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - list
        hash:
          $ref: '#/components/schemas/Word'
        maker:
          $ref: '#/components/schemas/Address'
        make:
          $ref: '#/components/schemas/Asset'
        take:
          $ref: '#/components/schemas/Asset'
        price:
          $ref: '#/components/schemas/BigDecimal'
      required:
      - price
      - take
      - make
      - maker
      - hash
      - '@type'
      additionalProperties: false
    OrderActivityMatch:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - match
        left:
          $ref: '#/components/schemas/OrderActivitySideMatch'
        right:
          $ref: '#/components/schemas/OrderActivitySideMatch'
        price:
          $ref: '#/components/schemas/BigDecimal'
        transactionHash:
          $ref: '#/components/schemas/Word'
        blockHash:
          $ref: '#/components/schemas/Word'
        blockNumber:
          $ref: '#/components/schemas/BlockNumber'
        logIndex:
          type: integer
          minimum: -1073741824
          maximum: 1073741823
      required:
      - logIndex
      - blockNumber
      - blockHash
      - transactionHash
      - price
      - right
      - left
      - '@type'
      additionalProperties: false
    OrderActivitySideMatch:
      type: object
      properties:
        maker:
          $ref: '#/components/schemas/Address'
        hash:
          $ref: '#/components/schemas/Word'
        asset:
          $ref: '#/components/schemas/Asset'
        type:
          $ref: '#/components/schemas/OrderActivitySideType'
      required:
      - type
      - asset
      - hash
      - maker
      additionalProperties: false
    OrderActivitySideType:
      type: string
      enum:
      - SELL
      - BID
    OrderActivityType:
      oneOf:
      - $ref: '#/components/schemas/OrderActivityMatch'
      - $ref: '#/components/schemas/OrderActivityList'
      - $ref: '#/components/schemas/OrderActivityBid'
      - $ref: '#/components/schemas/OrderActivityCancelBid'
      - $ref: '#/components/schemas/OrderActivityCancelList'
    OrderEvent:
      type: object
      properties:
        eventId:
          type: string
        orderId:
          type: string
        type:
          type: string
          enum:
          - UPDATE
        order:
          $ref: '#/components/schemas/Order'
      required:
      - order
      - type
      - orderId
      - eventId
      additionalProperties: false
    OrderPriceHistoryRecord:
      type: object
      properties:
        date:
          type: string
          format: date-time
        makeValue:
          $ref: '#/components/schemas/BigDecimal'
        takeValue:
          $ref: '#/components/schemas/BigDecimal'
      required:
      - takeValue
      - makeValue
      - date
      additionalProperties: false
    OrderRaribleV2DataV1:
      type: object
      properties:
        dataType:
          type: string
        payouts:
          type: array
          items:
            $ref: '#/components/schemas/Part'
        originFees:
          type: array
          items:
            $ref: '#/components/schemas/Part'
      required:
      - originFees
      - payouts
      - dataType
      additionalProperties: false
    OrderStatus:
      type: string
      enum:
      - ACTIVE
      - FILLED
      - HISTORICAL
      - INACTIVE
      - CANCELLED
    Part:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Address'
        value:
          type: integer
          minimum: 0
          maximum: 2147483647
      required:
      - value
      - account
      additionalProperties: false
    Transfer:
      type: object
      properties:
        '@type':
          type: string
          enum:
          - transfer
        elt:
          $ref: '#/components/schemas/NftActivityElt'
        from:
          $ref: '#/components/schemas/Address'
      required:
      - from
      - elt
      - '@type'
      additionalProperties: false
    Word:
      type: string
    XTZAssetType:
      type: object
      properties:
        assetClass:
          type: string
          enum:
          - XTZ
      required:
      - assetClass
      additionalProperties: false
  securitySchemes: {}
